// <auto-generated />
using System;
using Infrastructure.Database.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(MicarDbContext))]
    [Migration("20260919001949_AddNotificacaoVisualizadaToManutencao")]
    partial class AddNotificacaoVisualizadaToManutencao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Manutencoes.Manutencao", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date")
                        .HasColumnName("data");

                    b.Property<DateOnly?>("DataConclusao")
                        .HasColumnType("date")
                        .HasColumnName("data_conclusao");

                    b.Property<DateOnly?>("DataVencimento")
                        .HasColumnType("date")
                        .HasColumnName("data_vencimento");

                    b.Property<DateOnly?>("DataVisualizacaoNotificacaoAVencer")
                        .HasColumnType("date")
                        .HasColumnName("data_visualizacao_notificacao_a_vencer");

                    b.Property<DateOnly?>("DataVisualizacaoNotificacaoVencida")
                        .HasColumnType("date")
                        .HasColumnName("data_visualizacao_notificacao_vencida");

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<int?>("OdometroVencimento")
                        .HasColumnType("integer")
                        .HasColumnName("odometro_vencimento");

                    b.Property<decimal?>("Valor")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor");

                    b.Property<Guid>("VeiculoId")
                        .HasColumnType("uuid")
                        .HasColumnName("veiculo_id");

                    b.HasKey("Id")
                        .HasName("pk_manutencoes");

                    b.HasIndex("VeiculoId")
                        .HasDatabaseName("ix_manutencoes_veiculo_id");

                    b.ToTable("manutencoes", "public");
                });

            modelBuilder.Entity("Domain.PushTokens.PushToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Plataforma")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("plataforma");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_push_tokens");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_push_tokens_token");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_push_tokens_usuario_id");

                    b.ToTable("push_tokens", "public");
                });

            modelBuilder.Entity("Domain.RegistrosOdometro.RegistroOdometro", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date")
                        .HasColumnName("data");

                    b.Property<Guid?>("ManutencaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("manutencao_id");

                    b.Property<int>("Odometro")
                        .HasColumnType("integer")
                        .HasColumnName("odometro");

                    b.Property<Guid>("VeiculoId")
                        .HasColumnType("uuid")
                        .HasColumnName("veiculo_id");

                    b.HasKey("Id")
                        .HasName("pk_registros_odometro");

                    b.HasIndex("ManutencaoId")
                        .IsUnique()
                        .HasDatabaseName("ix_registros_odometro_manutencao_id");

                    b.HasIndex("VeiculoId")
                        .HasDatabaseName("ix_registros_odometro_veiculo_id");

                    b.ToTable("registros_odometro", "public");
                });

            modelBuilder.Entity("Domain.Usuarios.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("senha");

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_email");

                    b.ToTable("usuarios", "public");
                });

            modelBuilder.Entity("Domain.Veiculos.Veiculo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Apelido")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("apelido");

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<int>("DiasNotificacaoOdometro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(30)
                        .HasColumnName("dias_notificacao_odometro");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("placa");

                    b.Property<string>("TipoVeiculo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_veiculo");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_veiculos");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_veiculos_usuario_id");

                    b.ToTable("veiculos", "public");
                });

            modelBuilder.Entity("Domain.Manutencoes.Manutencao", b =>
                {
                    b.HasOne("Domain.Veiculos.Veiculo", "Veiculo")
                        .WithMany("Manutencoes")
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_manutencoes_veiculos_veiculo_id");

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("Domain.PushTokens.PushToken", b =>
                {
                    b.HasOne("Domain.Usuarios.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_push_tokens_usuarios_usuario_id");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Domain.RegistrosOdometro.RegistroOdometro", b =>
                {
                    b.HasOne("Domain.Manutencoes.Manutencao", "Manutencao")
                        .WithOne("RegistroOdometro")
                        .HasForeignKey("Domain.RegistrosOdometro.RegistroOdometro", "ManutencaoId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_registros_odometro_manutencoes_manutencao_id");

                    b.HasOne("Domain.Veiculos.Veiculo", "Veiculo")
                        .WithMany("RegistrosOdometro")
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_registros_odometro_veiculos_veiculo_id");

                    b.Navigation("Manutencao");

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("Domain.Veiculos.Veiculo", b =>
                {
                    b.HasOne("Domain.Usuarios.Usuario", "Usuario")
                        .WithMany("Veiculos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_veiculos_usuarios_usuario_id");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Domain.Manutencoes.Manutencao", b =>
                {
                    b.Navigation("RegistroOdometro");
                });

            modelBuilder.Entity("Domain.Usuarios.Usuario", b =>
                {
                    b.Navigation("Veiculos");
                });

            modelBuilder.Entity("Domain.Veiculos.Veiculo", b =>
                {
                    b.Navigation("Manutencoes");

                    b.Navigation("RegistrosOdometro");
                });
#pragma warning restore 612, 618
        }
    }
}
